version: '3.5'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      -'5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      -'6379:6379'
    volumes:
      - redis-data:/data

volumes:
  pg-data:
    name: pg-data
  redis-data:
    name: redis-data
